#
# GraphQL Query
# 
# Playground: http://localhost:1337/nitroapi/graphql
#


@GRAPHQL_ENDPOINT = /___gql
@BASE_URL = http://localhost:1337
@GRAPHQL_URL = {{BASE_URL}}{{GRAPHQL_ENDPOINT}}

@email = _test001_@local.host
@password = _test001_483184

# auth local
# @name loginReq
POST {{BASE_URL}}/auth/local HTTP/1.1
Content-Type: application/json

{
  "identifier": "{{email}}",
  "password": "{{password}}"
}
###
@authToken = {{loginReq.response.body.jwt}}
@userID = {{loginReq.response.body.user.id}}


# create an entry
# @name newEntryReq
POST {{GRAPHQL_URL}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{authToken}}
X-REQUEST-TYPE: GraphQL

mutation ($input: createJfactivityInput) {
  createJfactivity(input: $input) {
    jfactivity {
      id
    }
  }
}

{
  "input": { "data": {
    "devid": "012345678901234567890123",
    "actid":2415919107,
    "user": "{{userID}}"
  }}
}
###
@createdEntryID = {{newEntryReq.response.body.data.createJfactivity.jfactivity.id}}

# update
POST {{GRAPHQL_URL}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{authToken}}
X-REQUEST-TYPE: GraphQL

mutation ($input: updateJfactivityInput) {
  updateJfactivity(input: $input) {
    jfactivity {
      data
    }
  }
}

{
  "input": {
    "where": "{{createdEntryID}}",
    "data": {
      "data": ""
    },
  }
}
###
