
##
## Authentication
##

@BASE_URL = http://localhost:1337

# GET /bulletin-boards
GET {{BASE_URL}}/bulletin-boards/boards HTTP/1.1

###

# GET /count
GET {{BASE_URL}}/bulletin-boards/boards/count HTTP/1.1

###

# create a board
# POST /
# @name createBoard
POST {{BASE_URL}}/bulletin-boards/boards HTTP/1.1
Content-Type: application/json

{
  "name": "board-1",
  "allowReply": true
}
###
@bbid = {{createBoard.response.body.id}}

# GET /bulletin-boards/:id
GET {{BASE_URL}}/bulletin-boards/boards/{{bbid}} HTTP/1.1

###

# find articles
# GET /posts/:bbid
GET {{BASE_URL}}/bulletin-boards/posts/ HTTP/1.1

###

# article count
# GET /posts/:bbid/count
GET {{BASE_URL}}/bulletin-boards/posts/{{bbid}}/count HTTP/1.1

###

# create an article
# POST /posts/:bbid
# @name createArticle
POST {{BASE_URL}}/bulletin-boards/posts/{{bbid}} HTTP/1.1
Content-Type: application/json

{
  "title": "1",
  "content": "a"
}
###

# update an article
# PUT /posts/:bbid/:id
PUT {{BASE_URL}}/bulletin-boards/posts/{{bbid}}/{{createArticle.response.body.id}} HTTP/1.1
Content-Type: application/json

{
  "title": "1 updated",
  "content": "a updated"
}
###

# create a reply to the article
# POST /posts/:bbid/:pid
# @name createReply
POST {{BASE_URL}}/bulletin-boards/posts/{{bbid}}/{{createArticle.response.body.id}} HTTP/1.1
Content-Type: application/json

{
  "title": "1-1",
  "content": "a-1"
}
###

# update a reply
# PUT /posts/:bbid/:id
PUT {{BASE_URL}}/bulletin-boards/posts/{{bbid}}/{{createReply.response.body.id}} HTTP/1.1
Content-Type: application/json

{
  "title": "1-1 updated",
  "content": "a-1 updated"
}
###

# create a reply to the reply
# POST /posts/:bbid/:pid
POST {{BASE_URL}}/bulletin-boards/posts/{{bbid}}/{{createReply.response.body.id}} HTTP/1.1
Content-Type: application/json

{
  "title": "1-1-1",
  "content": "a-1-1"
}
###

# reply count
# GET /posts/:bbid/:pid/count
GET {{BASE_URL}}/bulletin-boards/posts/{{bbid}}/{{createArticle.response.body.id}}/count HTTP/1.1

###

# delete an article
# DELETE /posts/:bbid/:id
DELETE {{BASE_URL}}/bulletin-boards/posts/{{bbid}}/{{createArticle.response.body.id}} HTTP/1.1

###

# delete a reply
# DELETE /posts/:bbid/:id
DELETE {{BASE_URL}}/bulletin-boards/posts/{{bbid}}/{{createReply.response.body.id}} HTTP/1.1

###

# delete a board
# DELETE /boards/:id
DELETE {{BASE_URL}}/bulletin-boards/boards/{{bbid}}

###
