#
# Nginx Production Mode
#
# See https://docs.docker.com/engine/reference/builder/
#

# See https://hub.docker.com/_/nginx
FROM nginx:1.19.2-alpine

ARG volume_ro=/volume-ro
ARG volume_rw=/volume-rw

RUN echo "ARGs: volume_ro: ${volume_ro}, volume_rw: ${volume_rw}"

#
# directories
#

# read only
ENV NGINX_DIR "${volume_ro}/nginx-conf"
ENV PUBLIC_DIR "${volume_ro}/public"

# read-write
ENV LOG_DIR "${volume_rw}/log/nginx"

# volumes to be bound at runtime
VOLUME [ "${volume_ro}", "${volume_rw}" ]

#
# run
# use *shell form* for variable substitution
ENTRYPOINT nginx -c "$NGINX_DIR/nginx.conf" -g "daemon off;"
